# Generated by Django 4.0.5 on 2022-06-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=40)),
                ('product_img', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_stock', models.IntegerField()),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='')),
            ],
        ),
    ]
