# Generated by Django 4.0.4 on 2022-06-14 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stamp', models.DateTimeField()),
                ('complete', models.BooleanField()),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.warehouse')),
            ],
        ),
    ]
