# Generated by Django 4.0.5 on 2022-06-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
    ]
